"""Initial Schema with Cascade

Revision ID: 25da3e774331
Revises: 
Create Date: 2026-07-25 15:33:13.460988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25da3e774331'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('genero', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('livros',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('data_publicacao', sa.Date(), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('id_autor', sa.Integer(), nullable=False),
    sa.Column('id_genero', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_autor'], ['autores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_genero'], ['generos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('livros')
    op.drop_table('generos')
    op.drop_table('autores')
    # ### end Alembic commands ###
